# Generated by Django 6.0.4 on 2026-06-04 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=200)),
                ('stall_no', models.CharField(max_length=20)),
                ('contact_person', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('date_registered', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_registered'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('collection', 'Collection'), ('ledger', 'Ledger')], default='collection', max_length=20)),
                ('student_name', models.CharField(blank=True, max_length=200, null=True)),
                ('student_initials', models.CharField(blank=True, max_length=5, null=True)),
                ('grade_section', models.CharField(blank=True, max_length=100, null=True)),
                ('id_number', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('debit', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('credit', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('running_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('category', models.CharField(choices=[('Tuition', 'Tuition'), ('Supplies', 'Supplies'), ('Maintenance', 'Maintenance'), ('Utilities', 'Utilities'), ('Events', 'Events'), ('Payroll', 'Payroll'), ('Health', 'Health'), ('Other', 'Other')], default='Tuition', max_length=50)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('partial', 'Partial'), ('unpaid', 'Unpaid'), ('overdue', 'Overdue'), ('pending', 'Pending')], default='unpaid', max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
