# Generated by Django 6.0.4 on 2026-06-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_consignee_user_transaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(default='General', max_length=50),
        ),
    ]
