# Generated by Django 6.0.4 on 2026-06-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_liquidationreport_liquidationrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignee',
            name='school_year',
            field=models.CharField(db_index=True, default='2026-2027', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='school_year',
            field=models.CharField(default='2026-2027', max_length=20),
        ),
    ]
