# Generated by Django 6.0.4 on 2026-06-05 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_consignee_school_year_transaction_school_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='canteen',
            field=models.CharField(choices=[('Canteen 1', 'Canteen 1'), ('Canteen 2', 'Canteen 2')], db_index=True, default='Canteen 1', max_length=20),
        ),
    ]
