# Generated by Django 6.0.4 on 2026-06-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_transaction_canteen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignee',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
