# Generated by Django 6.0.4 on 2026-06-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignee',
            name='stall_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
