# Generated by Django 6.0.4 on 2026-06-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='canteen',
            field=models.CharField(choices=[('Canteen 1', 'Canteen 1'), ('Canteen 2', 'Canteen 2'), ('External', 'External')], db_index=True, default='Canteen 1', max_length=20),
        ),
    ]
