# Generated by Django 6.0.4 on 2026-06-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_transaction_canteen'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='requested_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
