# Generated by Django 6.0.4 on 2026-06-16 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_expense_requested_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquidationrow',
            name='report',
        ),
        migrations.DeleteModel(
            name='LiquidationReport',
        ),
        migrations.DeleteModel(
            name='LiquidationRow',
        ),
    ]
