# Generated by Django 6.0.4 on 2026-07-01 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_revenue_recipient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Liquidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(db_index=True, default='2026-2027', max_length=20)),
                ('month', models.CharField(db_index=True, max_length=7)),
                ('cash_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cash_withdrawn', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liquidations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['month'],
                'unique_together': {('school_year', 'month')},
            },
        ),
    ]
