# Generated by Django 6.0.4 on 2026-07-01 13:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_liquidation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='liquidation',
            unique_together={('user', 'school_year', 'month')},
        ),
    ]
