# Generated by Django 6.0.4 on 2026-07-06 14:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_cash_on_bank'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cashonbank',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cashonbank',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
