# Generated by Django 6.0.4 on 2026-07-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_cashreturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashreturn',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashreturn',
            name='returned_by',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='cashreturn',
            name='type',
            field=models.CharField(choices=[('Canteen', 'Canteen'), ('Coconut', 'Coconut')], default='Coconut', max_length=20),
        ),
    ]
