# Generated by Django 6.0.4 on 2026-07-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_cashreturn_reason_cashreturn_returned_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashonbank',
            options={'ordering': ['-date', '-updated_at']},
        ),
        migrations.AddField(
            model_name='cashonbank',
            name='type',
            field=models.CharField(choices=[('Canteen', 'Canteen'), ('Coconut', 'Coconut')], default='Canteen', max_length=20),
        ),
    ]
